---
queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - approved-reviews-by=zhaohuabing
pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - approved-reviews-by=zhaohuabing
    actions:
      queue:
        method: squash
        name: default
  - name: ask the maintainer team to review PR
    conditions:
      - and:
        - label!=invalid
        - -draft
    actions:
      request_reviews:
        users:
          - zhaohuabing
