---
queue_rules:
  - name: default
    queue_conditions:
      - approved-reviews-by=zhaohuabing
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - approved-reviews-by=zhaohuabing
    merge_method: squash

pull_request_rules:
  - name: ask the maintainer team to review PR
    conditions:
      - and:
          - label!=invalid
          - -draft
    actions:
      request_reviews:
        users:
          - zhaohuabing
  - name: Automatic merge on CI success and review
    conditions: []
    actions:
      queue:
