// Copyright Aeraki Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/aeraki-mesh/aeraki/client-go/pkg/apis/redis/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RedisServiceLister helps list RedisServices.
// All objects returned here must be treated as read-only.
type RedisServiceLister interface {
	// List lists all RedisServices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RedisService, err error)
	// RedisServices returns an object that can list and get RedisServices.
	RedisServices(namespace string) RedisServiceNamespaceLister
	RedisServiceListerExpansion
}

// redisServiceLister implements the RedisServiceLister interface.
type redisServiceLister struct {
	indexer cache.Indexer
}

// NewRedisServiceLister returns a new RedisServiceLister.
func NewRedisServiceLister(indexer cache.Indexer) RedisServiceLister {
	return &redisServiceLister{indexer: indexer}
}

// List lists all RedisServices in the indexer.
func (s *redisServiceLister) List(selector labels.Selector) (ret []*v1alpha1.RedisService, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RedisService))
	})
	return ret, err
}

// RedisServices returns an object that can list and get RedisServices.
func (s *redisServiceLister) RedisServices(namespace string) RedisServiceNamespaceLister {
	return redisServiceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RedisServiceNamespaceLister helps list and get RedisServices.
// All objects returned here must be treated as read-only.
type RedisServiceNamespaceLister interface {
	// List lists all RedisServices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RedisService, err error)
	// Get retrieves the RedisService from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.RedisService, error)
	RedisServiceNamespaceListerExpansion
}

// redisServiceNamespaceLister implements the RedisServiceNamespaceLister
// interface.
type redisServiceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RedisServices in the indexer for a given namespace.
func (s redisServiceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.RedisService, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RedisService))
	})
	return ret, err
}

// Get retrieves the RedisService from the indexer for a given namespace and name.
func (s redisServiceNamespaceLister) Get(name string) (*v1alpha1.RedisService, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("redisservice"), name)
	}
	return obj.(*v1alpha1.RedisService), nil
}
