// Copyright Aeraki Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/aeraki-mesh/aeraki/client-go/pkg/apis/redis/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RedisDestinationLister helps list RedisDestinations.
// All objects returned here must be treated as read-only.
type RedisDestinationLister interface {
	// List lists all RedisDestinations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RedisDestination, err error)
	// RedisDestinations returns an object that can list and get RedisDestinations.
	RedisDestinations(namespace string) RedisDestinationNamespaceLister
	RedisDestinationListerExpansion
}

// redisDestinationLister implements the RedisDestinationLister interface.
type redisDestinationLister struct {
	indexer cache.Indexer
}

// NewRedisDestinationLister returns a new RedisDestinationLister.
func NewRedisDestinationLister(indexer cache.Indexer) RedisDestinationLister {
	return &redisDestinationLister{indexer: indexer}
}

// List lists all RedisDestinations in the indexer.
func (s *redisDestinationLister) List(selector labels.Selector) (ret []*v1alpha1.RedisDestination, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RedisDestination))
	})
	return ret, err
}

// RedisDestinations returns an object that can list and get RedisDestinations.
func (s *redisDestinationLister) RedisDestinations(namespace string) RedisDestinationNamespaceLister {
	return redisDestinationNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RedisDestinationNamespaceLister helps list and get RedisDestinations.
// All objects returned here must be treated as read-only.
type RedisDestinationNamespaceLister interface {
	// List lists all RedisDestinations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RedisDestination, err error)
	// Get retrieves the RedisDestination from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.RedisDestination, error)
	RedisDestinationNamespaceListerExpansion
}

// redisDestinationNamespaceLister implements the RedisDestinationNamespaceLister
// interface.
type redisDestinationNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RedisDestinations in the indexer for a given namespace.
func (s redisDestinationNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.RedisDestination, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RedisDestination))
	})
	return ret, err
}

// Get retrieves the RedisDestination from the indexer for a given namespace and name.
func (s redisDestinationNamespaceLister) Get(name string) (*v1alpha1.RedisDestination, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("redisdestination"), name)
	}
	return obj.(*v1alpha1.RedisDestination), nil
}
