// Copyright Aeraki Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/aeraki-mesh/aeraki/client-go/pkg/apis/redis/v1alpha1"
	scheme "github.com/aeraki-mesh/aeraki/client-go/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RedisServicesGetter has a method to return a RedisServiceInterface.
// A group's client should implement this interface.
type RedisServicesGetter interface {
	RedisServices(namespace string) RedisServiceInterface
}

// RedisServiceInterface has methods to work with RedisService resources.
type RedisServiceInterface interface {
	Create(ctx context.Context, redisService *v1alpha1.RedisService, opts v1.CreateOptions) (*v1alpha1.RedisService, error)
	Update(ctx context.Context, redisService *v1alpha1.RedisService, opts v1.UpdateOptions) (*v1alpha1.RedisService, error)
	UpdateStatus(ctx context.Context, redisService *v1alpha1.RedisService, opts v1.UpdateOptions) (*v1alpha1.RedisService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RedisService, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RedisServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RedisService, err error)
	RedisServiceExpansion
}

// redisServices implements RedisServiceInterface
type redisServices struct {
	client rest.Interface
	ns     string
}

// newRedisServices returns a RedisServices
func newRedisServices(c *RedisV1alpha1Client, namespace string) *redisServices {
	return &redisServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the redisService, and returns the corresponding redisService object, and an error if there is any.
func (c *redisServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RedisService, err error) {
	result = &v1alpha1.RedisService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("redisservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RedisServices that match those selectors.
func (c *redisServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RedisServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RedisServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("redisservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested redisServices.
func (c *redisServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("redisservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a redisService and creates it.  Returns the server's representation of the redisService, and an error, if there is any.
func (c *redisServices) Create(ctx context.Context, redisService *v1alpha1.RedisService, opts v1.CreateOptions) (result *v1alpha1.RedisService, err error) {
	result = &v1alpha1.RedisService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("redisservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(redisService).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a redisService and updates it. Returns the server's representation of the redisService, and an error, if there is any.
func (c *redisServices) Update(ctx context.Context, redisService *v1alpha1.RedisService, opts v1.UpdateOptions) (result *v1alpha1.RedisService, err error) {
	result = &v1alpha1.RedisService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("redisservices").
		Name(redisService.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(redisService).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *redisServices) UpdateStatus(ctx context.Context, redisService *v1alpha1.RedisService, opts v1.UpdateOptions) (result *v1alpha1.RedisService, err error) {
	result = &v1alpha1.RedisService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("redisservices").
		Name(redisService.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(redisService).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the redisService and deletes it. Returns an error if one occurs.
func (c *redisServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("redisservices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *redisServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("redisservices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched redisService.
func (c *redisServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RedisService, err error) {
	result = &v1alpha1.RedisService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("redisservices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
