// Copyright Aeraki Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/aeraki-mesh/aeraki/client-go/pkg/apis/redis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRedisServices implements RedisServiceInterface
type FakeRedisServices struct {
	Fake *FakeRedisV1alpha1
	ns   string
}

var redisservicesResource = schema.GroupVersionResource{Group: "redis.aeraki.io", Version: "v1alpha1", Resource: "redisservices"}

var redisservicesKind = schema.GroupVersionKind{Group: "redis.aeraki.io", Version: "v1alpha1", Kind: "RedisService"}

// Get takes name of the redisService, and returns the corresponding redisService object, and an error if there is any.
func (c *FakeRedisServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RedisService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(redisservicesResource, c.ns, name), &v1alpha1.RedisService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisService), err
}

// List takes label and field selectors, and returns the list of RedisServices that match those selectors.
func (c *FakeRedisServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RedisServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(redisservicesResource, redisservicesKind, c.ns, opts), &v1alpha1.RedisServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RedisServiceList{ListMeta: obj.(*v1alpha1.RedisServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.RedisServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested redisServices.
func (c *FakeRedisServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(redisservicesResource, c.ns, opts))

}

// Create takes the representation of a redisService and creates it.  Returns the server's representation of the redisService, and an error, if there is any.
func (c *FakeRedisServices) Create(ctx context.Context, redisService *v1alpha1.RedisService, opts v1.CreateOptions) (result *v1alpha1.RedisService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(redisservicesResource, c.ns, redisService), &v1alpha1.RedisService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisService), err
}

// Update takes the representation of a redisService and updates it. Returns the server's representation of the redisService, and an error, if there is any.
func (c *FakeRedisServices) Update(ctx context.Context, redisService *v1alpha1.RedisService, opts v1.UpdateOptions) (result *v1alpha1.RedisService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(redisservicesResource, c.ns, redisService), &v1alpha1.RedisService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRedisServices) UpdateStatus(ctx context.Context, redisService *v1alpha1.RedisService, opts v1.UpdateOptions) (*v1alpha1.RedisService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(redisservicesResource, "status", c.ns, redisService), &v1alpha1.RedisService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisService), err
}

// Delete takes name of the redisService and deletes it. Returns an error if one occurs.
func (c *FakeRedisServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(redisservicesResource, c.ns, name), &v1alpha1.RedisService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRedisServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(redisservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RedisServiceList{})
	return err
}

// Patch applies the patch and returns the patched redisService.
func (c *FakeRedisServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RedisService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(redisservicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.RedisService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RedisService), err
}
