// Copyright Aeraki Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/aeraki-mesh/aeraki/client-go/pkg/apis/dubbo/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDubboAuthorizationPolicies implements DubboAuthorizationPolicyInterface
type FakeDubboAuthorizationPolicies struct {
	Fake *FakeDubboV1alpha1
	ns   string
}

var dubboauthorizationpoliciesResource = schema.GroupVersionResource{Group: "dubbo.aeraki.io", Version: "v1alpha1", Resource: "dubboauthorizationpolicies"}

var dubboauthorizationpoliciesKind = schema.GroupVersionKind{Group: "dubbo.aeraki.io", Version: "v1alpha1", Kind: "DubboAuthorizationPolicy"}

// Get takes name of the dubboAuthorizationPolicy, and returns the corresponding dubboAuthorizationPolicy object, and an error if there is any.
func (c *FakeDubboAuthorizationPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DubboAuthorizationPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dubboauthorizationpoliciesResource, c.ns, name), &v1alpha1.DubboAuthorizationPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DubboAuthorizationPolicy), err
}

// List takes label and field selectors, and returns the list of DubboAuthorizationPolicies that match those selectors.
func (c *FakeDubboAuthorizationPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DubboAuthorizationPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dubboauthorizationpoliciesResource, dubboauthorizationpoliciesKind, c.ns, opts), &v1alpha1.DubboAuthorizationPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DubboAuthorizationPolicyList{ListMeta: obj.(*v1alpha1.DubboAuthorizationPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.DubboAuthorizationPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dubboAuthorizationPolicies.
func (c *FakeDubboAuthorizationPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dubboauthorizationpoliciesResource, c.ns, opts))

}

// Create takes the representation of a dubboAuthorizationPolicy and creates it.  Returns the server's representation of the dubboAuthorizationPolicy, and an error, if there is any.
func (c *FakeDubboAuthorizationPolicies) Create(ctx context.Context, dubboAuthorizationPolicy *v1alpha1.DubboAuthorizationPolicy, opts v1.CreateOptions) (result *v1alpha1.DubboAuthorizationPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dubboauthorizationpoliciesResource, c.ns, dubboAuthorizationPolicy), &v1alpha1.DubboAuthorizationPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DubboAuthorizationPolicy), err
}

// Update takes the representation of a dubboAuthorizationPolicy and updates it. Returns the server's representation of the dubboAuthorizationPolicy, and an error, if there is any.
func (c *FakeDubboAuthorizationPolicies) Update(ctx context.Context, dubboAuthorizationPolicy *v1alpha1.DubboAuthorizationPolicy, opts v1.UpdateOptions) (result *v1alpha1.DubboAuthorizationPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dubboauthorizationpoliciesResource, c.ns, dubboAuthorizationPolicy), &v1alpha1.DubboAuthorizationPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DubboAuthorizationPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDubboAuthorizationPolicies) UpdateStatus(ctx context.Context, dubboAuthorizationPolicy *v1alpha1.DubboAuthorizationPolicy, opts v1.UpdateOptions) (*v1alpha1.DubboAuthorizationPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dubboauthorizationpoliciesResource, "status", c.ns, dubboAuthorizationPolicy), &v1alpha1.DubboAuthorizationPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DubboAuthorizationPolicy), err
}

// Delete takes name of the dubboAuthorizationPolicy and deletes it. Returns an error if one occurs.
func (c *FakeDubboAuthorizationPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dubboauthorizationpoliciesResource, c.ns, name), &v1alpha1.DubboAuthorizationPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDubboAuthorizationPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dubboauthorizationpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DubboAuthorizationPolicyList{})
	return err
}

// Patch applies the patch and returns the patched dubboAuthorizationPolicy.
func (c *FakeDubboAuthorizationPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DubboAuthorizationPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dubboauthorizationpoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DubboAuthorizationPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DubboAuthorizationPolicy), err
}
