// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/redis/v1alpha1/redisservice.proto

// `RedisService` provide a way to config redis service in service mesh.

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "istio.io/gogo-genproto/googleapis/google/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using RedisService within kubernetes types, where deepcopy-gen is used.
func (in *RedisService) DeepCopyInto(out *RedisService) {
	p := proto.Clone(in).(*RedisService)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisService. Required by controller-gen.
func (in *RedisService) DeepCopy() *RedisService {
	if in == nil {
		return nil
	}
	out := new(RedisService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RedisService. Required by controller-gen.
func (in *RedisService) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RedisService_Settings within kubernetes types, where deepcopy-gen is used.
func (in *RedisService_Settings) DeepCopyInto(out *RedisService_Settings) {
	p := proto.Clone(in).(*RedisService_Settings)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisService_Settings. Required by controller-gen.
func (in *RedisService_Settings) DeepCopy() *RedisService_Settings {
	if in == nil {
		return nil
	}
	out := new(RedisService_Settings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RedisService_Settings. Required by controller-gen.
func (in *RedisService_Settings) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RedisService_KeyMatch within kubernetes types, where deepcopy-gen is used.
func (in *RedisService_KeyMatch) DeepCopyInto(out *RedisService_KeyMatch) {
	p := proto.Clone(in).(*RedisService_KeyMatch)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisService_KeyMatch. Required by controller-gen.
func (in *RedisService_KeyMatch) DeepCopy() *RedisService_KeyMatch {
	if in == nil {
		return nil
	}
	out := new(RedisService_KeyMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RedisService_KeyMatch. Required by controller-gen.
func (in *RedisService_KeyMatch) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RedisService_RouteMatch within kubernetes types, where deepcopy-gen is used.
func (in *RedisService_RouteMatch) DeepCopyInto(out *RedisService_RouteMatch) {
	p := proto.Clone(in).(*RedisService_RouteMatch)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisService_RouteMatch. Required by controller-gen.
func (in *RedisService_RouteMatch) DeepCopy() *RedisService_RouteMatch {
	if in == nil {
		return nil
	}
	out := new(RedisService_RouteMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RedisService_RouteMatch. Required by controller-gen.
func (in *RedisService_RouteMatch) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RedisService_Destination within kubernetes types, where deepcopy-gen is used.
func (in *RedisService_Destination) DeepCopyInto(out *RedisService_Destination) {
	p := proto.Clone(in).(*RedisService_Destination)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisService_Destination. Required by controller-gen.
func (in *RedisService_Destination) DeepCopy() *RedisService_Destination {
	if in == nil {
		return nil
	}
	out := new(RedisService_Destination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RedisService_Destination. Required by controller-gen.
func (in *RedisService_Destination) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RedisService_Mirror within kubernetes types, where deepcopy-gen is used.
func (in *RedisService_Mirror) DeepCopyInto(out *RedisService_Mirror) {
	p := proto.Clone(in).(*RedisService_Mirror)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisService_Mirror. Required by controller-gen.
func (in *RedisService_Mirror) DeepCopy() *RedisService_Mirror {
	if in == nil {
		return nil
	}
	out := new(RedisService_Mirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RedisService_Mirror. Required by controller-gen.
func (in *RedisService_Mirror) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RedisService_Route within kubernetes types, where deepcopy-gen is used.
func (in *RedisService_Route) DeepCopyInto(out *RedisService_Route) {
	p := proto.Clone(in).(*RedisService_Route)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisService_Route. Required by controller-gen.
func (in *RedisService_Route) DeepCopy() *RedisService_Route {
	if in == nil {
		return nil
	}
	out := new(RedisService_Route)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RedisService_Route. Required by controller-gen.
func (in *RedisService_Route) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Percent within kubernetes types, where deepcopy-gen is used.
func (in *Percent) DeepCopyInto(out *Percent) {
	p := proto.Clone(in).(*Percent)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Percent. Required by controller-gen.
func (in *Percent) DeepCopy() *Percent {
	if in == nil {
		return nil
	}
	out := new(Percent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Percent. Required by controller-gen.
func (in *Percent) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Fault within kubernetes types, where deepcopy-gen is used.
func (in *Fault) DeepCopyInto(out *Fault) {
	p := proto.Clone(in).(*Fault)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Fault. Required by controller-gen.
func (in *Fault) DeepCopy() *Fault {
	if in == nil {
		return nil
	}
	out := new(Fault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Fault. Required by controller-gen.
func (in *Fault) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
