// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/redis/v1alpha1/redisservice.proto

// `RedisService` provide a way to config redis service in service mesh.

package v1alpha1

import (
	bytes "bytes"
	fmt "fmt"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "istio.io/gogo-genproto/googleapis/google/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for RedisService
func (this *RedisService) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService
func (this *RedisService) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisService_Settings
func (this *RedisService_Settings) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService_Settings
func (this *RedisService_Settings) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisService_KeyMatch
func (this *RedisService_KeyMatch) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService_KeyMatch
func (this *RedisService_KeyMatch) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisService_RouteMatch
func (this *RedisService_RouteMatch) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService_RouteMatch
func (this *RedisService_RouteMatch) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisService_Destination
func (this *RedisService_Destination) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService_Destination
func (this *RedisService_Destination) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisService_Mirror
func (this *RedisService_Mirror) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService_Mirror
func (this *RedisService_Mirror) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RedisService_Route
func (this *RedisService_Route) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RedisService_Route
func (this *RedisService_Route) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Percent
func (this *Percent) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Percent
func (this *Percent) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Fault
func (this *Fault) MarshalJSON() ([]byte, error) {
	str, err := RedisserviceMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Fault
func (this *Fault) UnmarshalJSON(b []byte) error {
	return RedisserviceUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	RedisserviceMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	RedisserviceUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{AllowUnknownFields: true}
)
