# Copyright Aeraki Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-cat-producer
spec:
  selector:
    matchLabels:
      app: kafka-cat-producer
  template:
    metadata:
      labels:
        app: kafka-cat-producer
    spec:
      containers:
        - name: kafka-cat-producer
          image: confluentinc/cp-kafkacat
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "while true; do  echo -e 'send kafka message '`date`'\r\n'|kafkacat -P  -b my-release-kafka:9092 -t test; echo 'send message to kafka'; sleep $((1 + RANDOM % 11)); done"]
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-cat-consumer
spec:
  selector:
    matchLabels:
      app: kafka-cat-consumer
  template:
    metadata:
      labels:
        app: kafka-cat-consumer
    spec:
      containers:
        - name: kafka-cat-consumer
          image: confluentinc/cp-kafkacat
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "while true; do kafkacat -C -b my-release-kafka:9092 -t test ; sleep 5; done"]
