{
 "title": "Aeraki Demo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Thrift Request Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_meta_protocol_thrift_outbound_9090__thrift_sample_server_meta_thrift_svc_cluster_local_request[5m]))"
    }
   ]
  },
  {
   "title": "Dubbo Request Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_meta_protocol_dubbo_outbound_20880__org_apache_dubbo_samples_basic_api_demoservice_request[5m]))"
    }
   ]
  },
  {
   "title": "Thrift  Request Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_meta_protocol_thrift_outbound_9090__thrift_sample_server_meta_thrift_svc_cluster_local_request_time_ms_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Dubbo Request Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_meta_protocol_dubbo_outbound_20880__org_apache_dubbo_samples_basic_api_demoservice_request_time_ms_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Thrift Request Latency Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "envoy_meta_protocol_thrift_outbound_9090__thrift_sample_server_meta_thrift_svc_cluster_local_request_time_ms_bucket{le=\"10\",app=\"thrift-sample-client\"}/ignoring (le) envoy_meta_protocol_thrift_outbound_9090__thrift_sample_server_meta_thrift_svc_cluster_local_request_time_ms_count *100",
     "legendFormat": "Less than 10 ms"
    },
    {
     "expr": "envoy_meta_protocol_thrift_outbound_9090__thrift_sample_server_meta_thrift_svc_cluster_local_request_time_ms_bucket{le=\"100\",app=\"thrift-sample-client\"}/ignoring (le) envoy_meta_protocol_thrift_outbound_9090__thrift_sample_server_meta_thrift_svc_cluster_local_request_time_ms_count *100",
     "legendFormat": "Less than 100 ms"
    },
    {
     "expr": "envoy_meta_protocol_thrift_outbound_9090__thrift_sample_server_meta_thrift_svc_cluster_local_request_time_ms_bucket{le=\"1000\",app=\"thrift-sample-client\"}/ignoring (le) envoy_meta_protocol_thrift_outbound_9090__thrift_sample_server_meta_thrift_svc_cluster_local_request_time_ms_count *100",
     "legendFormat": "Less than 1 s"
    },
    {
     "expr": "envoy_meta_protocol_thrift_outbound_9090__thrift_sample_server_meta_thrift_svc_cluster_local_request_time_ms_bucket{le=\"10000\",app=\"thrift-sample-client\"}/ignoring (le) envoy_meta_protocol_thrift_outbound_9090__thrift_sample_server_meta_thrift_svc_cluster_local_request_time_ms_count *100",
     "legendFormat": "Less than 10 s"
    }
   ]
  },
  {
   "title": "Dubbo Request Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "envoy_meta_protocol_dubbo_outbound_20880__org_apache_dubbo_samples_basic_api_demoservice_request_time_ms_bucket{le=\"10\",app=\"dubbo-sample-consumer\"}/ignoring (le) envoy_meta_protocol_dubbo_outbound_20880__org_apache_dubbo_samples_basic_api_demoservice_request_time_ms_count *100",
     "legendFormat": "Less than 10 ms"
    },
    {
     "expr": "envoy_meta_protocol_dubbo_outbound_20880__org_apache_dubbo_samples_basic_api_demoservice_request_time_ms_bucket{le=\"100\",app=\"dubbo-sample-consumer\"}/ignoring (le) envoy_meta_protocol_dubbo_outbound_20880__org_apache_dubbo_samples_basic_api_demoservice_request_time_ms_count *100",
     "legendFormat": "Less than 100 ms"
    },
    {
     "expr": "envoy_meta_protocol_dubbo_outbound_20880__org_apache_dubbo_samples_basic_api_demoservice_request_time_ms_bucket{le=\"1000\",app=\"dubbo-sample-consumer\"}/ignoring (le) envoy_meta_protocol_dubbo_outbound_20880__org_apache_dubbo_samples_basic_api_demoservice_request_time_ms_count *100",
     "legendFormat": "Less than 1 s"
    },
    {
     "expr": "envoy_meta_protocol_dubbo_outbound_20880__org_apache_dubbo_samples_basic_api_demoservice_request_time_ms_bucket{le=\"10000\",app=\"dubbo-sample-consumer\"}/ignoring (le) envoy_meta_protocol_dubbo_outbound_20880__org_apache_dubbo_samples_basic_api_demoservice_request_time_ms_count *100",
     "legendFormat": "Less than 10 s"
    }
   ]
  },
  {
   "title": "Thrift Request Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_meta_protocol_thrift_outbound_9090__thrift_sample_server_meta_thrift_svc_cluster_local_response_success[5m]))/sum(rate(envoy_meta_protocol_thrift_outbound_9090__thrift_sample_server_meta_thrift_svc_cluster_local_request[5m]))*100"
    }
   ]
  },
  {
   "title": "Dubbo Call Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_meta_protocol_dubbo_outbound_20880__org_apache_dubbo_samples_basic_api_demoservice_response_success[5m]))/sum(rate(envoy_meta_protocol_dubbo_outbound_20880__org_apache_dubbo_samples_basic_api_demoservice_request[5m]))*100"
    }
   ]
  },
  {
   "title": "Zookeeper GetData Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_getdata_resp_latency_bucket{le=\"1\", statefulset_kubernetes_io_pod_name=\"my-release-kafka-0\"} / ignoring (le) envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_getdata_resp_latency_count *100",
     "legendFormat": "Less than 1 ms"
    },
    {
     "expr": "envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_getdata_resp_latency_bucket{le=\"10\", statefulset_kubernetes_io_pod_name=\"my-release-kafka-0\"} / ignoring (le) envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_getdata_resp_latency_count *100",
     "legendFormat": "Less than 10 ms"
    },
    {
     "expr": "envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_getdata_resp_latency_bucket{le=\"100\", statefulset_kubernetes_io_pod_name=\"my-release-kafka-0\"} / ignoring (le) envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_getdata_resp_latency_count *100",
     "legendFormat": "Less than 100 ms"
    },
    {
     "expr": "envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_getdata_resp_latency_bucket{le=\"1000\", statefulset_kubernetes_io_pod_name=\"my-release-kafka-0\"} / ignoring (le) envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_getdata_resp_latency_count *100",
     "legendFormat": "Less than 1 m"
    }
   ]
  },
  {
   "title": "Zookeeper Create Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_create_resp_latency_bucket{le=\"1\", statefulset_kubernetes_io_pod_name=\"my-release-kafka-0\"} / ignoring (le) envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_create_resp_latency_count *100",
     "legendFormat": "Less than 1 ms"
    },
    {
     "expr": "envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_create_resp_latency_bucket{le=\"10\", statefulset_kubernetes_io_pod_name=\"my-release-kafka-0\"} / ignoring (le) envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_create_resp_latency_count *100",
     "legendFormat": "Less than 10 ms"
    },
    {
     "expr": "envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_create_resp_latency_bucket{le=\"100\", statefulset_kubernetes_io_pod_name=\"my-release-kafka-0\"} / ignoring (le) envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_create_resp_latency_count *100",
     "legendFormat": "Less than 100 ms"
    },
    {
     "expr": "envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_create_resp_latency_bucket{le=\"1000\", statefulset_kubernetes_io_pod_name=\"my-release-kafka-0\"} / ignoring (le) envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_create_resp_latency_count *100",
     "legendFormat": "Less than 1 m"
    }
   ]
  },
  {
   "title": "Zookeeper Ping Latency ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_ping_response_latency_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Zookeeper Ping Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_outbound_2181__my_release_zookeeper_kafka_svc_cluster_local_zookeeper_ping_resp[5m]))"
    }
   ]
  }
 ]
}