---
name: e2e-kafka-zookeeper

on: [push, pull_request]

env:
  ISTIO_VERSION: 1.12.7
  SCRIPTS_DIR: test/e2e/scripts
  COMMON_DIR: test/e2e/common

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: true
    name: e2e-test
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: |
          go version
          go get golang.org/x/tools/cmd/goimports
      - name: build docker
        run: make docker-build-e2e
      - name: Prepare envrionment
        run: bash ${SCRIPTS_DIR}/pre.sh
      - name: Install Minikube
        run: bash ${SCRIPTS_DIR}/minikube.sh start
      - name: Install Istio
        run: bash ${SCRIPTS_DIR}/istio.sh -y -f ${COMMON_DIR}/istio-config.yaml
      - name: Install aeraki
        run: bash ${SCRIPTS_DIR}/aeraki.sh
      - name: test
        run: make e2e-kafka-zookeeper
